name: Generate Sitemap and Robots.txt

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build site (Next.js + Contentlayer)
        run: npm run build
        env:
          SITE_URL: https://jet-lab.site
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - name: Generate sitemap
        run: node generate-sitemap.mjs
        env:
          SITE_URL: https://jet-lab.site

      - name: Create robots.txt
        run: |
          echo "User-agent: *" > public/robots.txt
          echo "Allow: /" >> public/robots.txt
          echo "Sitemap: https://jet-lab.site/sitemap.xml" >> public/robots.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/sitemap*.xml public/robots.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: generate sitemap and robots.txt [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
